services:
  postgres:
    image: postgres:latest
    container_name: asos_DB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asos
    volumes:
      - ./src/main/resources/init-sql:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"